version: "3.9"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: splendor-backend
    ports:
      - "8877:8080"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: splendor-frontend
    ports:
      - "7788:80"
    depends_on:
      - backend
    restart: unless-stopped
